name: lofi_frontend
description: "구해조! - 분실물 퀴즈 매칭 서비스"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.3
  provider: ^6.1.2
  shared_preferences: ^2.3.5
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo_T.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo_T.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/app_logo_T.png
    - assets/app_logo_f.png
    - assets/app_logo_T_white_N.png
    - assets/상단배경.png
    - assets/지도.png
    - assets/찾아주세요.png
    - assets/습득물등록.png
    - assets/남성.png
    - assets/여성.png
    - assets/돋보기.png
    - assets/즐겨찾기.png
    - assets/채팅.png
